Shop/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Cart;
using Shop.Data.Services;
using Shop.Data.Static;
using Shop.Data.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly ISongsService _songsService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;

        public OrdersController(ISongsService songsService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _songsService = songsService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                ;
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId,userRole);
            return View(orders);

        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal= _shoppingCart.GetShoppingCartTotal()
            };
            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _songsService.GetSongByIdAsync(id);
            if(item !=null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _songsService.GetSongByIdAsync(id);
            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email); ;

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();
            return View("OrderCompleted");
        }
    }
}

Shop/Controllers/ProducersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shop.Data;
using Shop.Data.Services;
using Shop.Data.Static;
using Shop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    [Authorize(Roles =UserRoles.Admin)]
    public class ProducersController : Controller
    {
        private readonly IProducersService _service;

        public ProducersController(IProducersService service)
        {
            _service = service;
        }
        [AllowAnonymous]
        public  async Task<IActionResult> Index()
        {
            var allProducers = await _service.GetAllAsync();
            return View(allProducers);
        }

        //GET: producers/details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");
            return View(producerDetails);
        }

        //GET: producers/create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ProfilePictureUrl,FullName,Bio")]Producer producer)
        {
            if (!ModelState.IsValid) return View(producer);

            await _service.AddAsync(producer);
            return RedirectToAction(nameof(Index));
        }

        //GET: producers/edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");
            return View(producerDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProfilePictureUrl,FullName,Bio")] Producer producer)
        {
            if (!ModelState.IsValid) return View(producer);

            if(id == producer.Id)
            {
                await _service.UpdateAsync(id, producer);
                return RedirectToAction(nameof(Index));

            }
            return View(producer);
            
            
        }

        //GET: producers/delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");
            return View(producerDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));

        }
    }
}

Shop/Controllers/SingersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shop.Data;
using Shop.Data.Services;
using Shop.Data.Static;
using Shop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class SingersController : Controller
    {
        private readonly ISingersService _service;

        public SingersController(ISingersService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        //Get: Singers/Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureUrl,Bio")]Singer singer)
        {
            if (!ModelState.IsValid)
            {
                return View(singer);
            }
            await _service.AddAsync(singer);
            return RedirectToAction(nameof(Index));
        }

        //Get: Singers/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var singerDetails = await _service.GetByIdAsync(id);

            if (singerDetails == null) return View("NotFound");
            return View(singerDetails);
        }

        //Get: Singers/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var singerDetails = await _service.GetByIdAsync(id);

            if (singerDetails == null) return View("NotFound");
            return View(singerDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("FullName,ProfilePictureUrl,Bio")] Singer singer)
        {
            if (!ModelState.IsValid)
            {
                return View(singer);
            }
            await _service.UpdateAsync(id, singer);
            return RedirectToAction(nameof(Index));
        }

        //Get: Singers/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var singerDetails = await _service.GetByIdAsync(id);

            if (singerDetails == null) return View("NotFound");
            return View(singerDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var singerDetails = await _service.GetByIdAsync(id);
            if (singerDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Shop/Controllers/SongsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Shop.Data;
using Shop.Data.Services;
using Shop.Data.Static;
using Shop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class SongsController : Controller
    {
        private readonly ISongsService _service;

        public SongsController(ISongsService service)
        {
            _service = service;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allSongs = await _service.GetAllAsync(n => n.RecordLabel);
            return View(allSongs);
        }
        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var allSongs = await _service.GetAllAsync(n => n.RecordLabel);

            if(!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allSongs.Where(n => n.Name.Contains(searchString) || n.FullName.Contains(searchString)).ToList();
                return View("Index", filteredResult);
            }


            return View("Index", allSongs);
        }

        //GET: Songs/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var songDetail = await _service.GetSongByIdAsync(id);
            return View(songDetail);
        }

        //GET: Songs/Create
        public async Task<IActionResult> Create()
        {
            var songDropdownsData = await _service.GetNewSongDropdownsValue();

            ViewBag.Labels = new SelectList(songDropdownsData.Labels, "Id", "Name");
            ViewBag.Producers = new SelectList(songDropdownsData.Producers, "Id", "FullName");
            ViewBag.Singers = new SelectList(songDropdownsData.Singers, "Id", "FullName");

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(NewSongVM song)
        {
            if(!ModelState.IsValid)
            {
                var songDropdownsData = await _service.GetNewSongDropdownsValue();
                ViewBag.Labels = new SelectList(songDropdownsData.Labels, "Id", "Name");
                ViewBag.Producers = new SelectList(songDropdownsData.Producers, "Id", "FullName");
                ViewBag.Singers = new SelectList(songDropdownsData.Singers, "Id", "FullName");
                return View(song);
            }
            await _service.AddNewSongAsync(song);
            return RedirectToAction(nameof(Index));
        }

        //GET: Songs/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var songDetails = await _service.GetSongByIdAsync(id);
            if (songDetails == null) return View("NotFound");

            var response = new NewSongVM()
            {
                Id=songDetails.Id,
                Name = songDetails.Name,
                FullName = songDetails.FullName,
                Price = songDetails.Price,
                ImageUrl = songDetails.ImageUrl,
                RecordLabelId = songDetails.RecordLabelId,
                SongCategory = songDetails.SongCategory,
                ProducerId = songDetails.ProducerId,
                SingerIds = songDetails.Singers_Songs.Select(n=>n.SingerId).ToList(),
            };

            var songDropdownsData = await _service.GetNewSongDropdownsValue();

            ViewBag.Labels = new SelectList(songDropdownsData.Labels, "Id", "Name");
            ViewBag.Producers = new SelectList(songDropdownsData.Producers, "Id", "FullName");
            ViewBag.Singers = new SelectList(songDropdownsData.Singers, "Id", "FullName");

            return View(response);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewSongVM song)
        {
            if (id != song.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var songDropdownsData = await _service.GetNewSongDropdownsValue();
                ViewBag.Labels = new SelectList(songDropdownsData.Labels, "Id", "Name");
                ViewBag.Producers = new SelectList(songDropdownsData.Producers, "Id", "FullName");
                ViewBag.Singers = new SelectList(songDropdownsData.Singers, "Id", "FullName");
                return View(song);
            }
            await _service.UpdateSongAsync(song);
            return RedirectToAction(nameof(Index));
        }
    }
}

Shop/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info"> You've reached the end of the internet!</h1>
        <hr/>
        <a class="btn btn-outline-success" asp-controller="Songs" asp-action="Index">Home Page</a>
    </div>   
</div>

Shop/Views/Shared/_CreateItem.cshtml
@model string;
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
<div style="position:fixed; right: 25px; bottom: 70px;" class="text-white">
    <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
        <i class="bi bi-plus-circle"></i>Add New
    </a>
</div>
}
    

Shop/Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager;


@if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Log in
    </a>
    <span style="padding:5px;"></span>
    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Register
    </a>

}
else
{
    @*User Profile Section*@
    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-badge"></i> Hello @UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-label="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                    <i class="bi bi-list"></i>Orders
                </a>
            </li>
            @if (User.IsInRole("Admin")) {
            <li>
                <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                    <i class="bi bi-people"></i>Users
                </a>
            </li>
            }

        </ul>
    </div>

    <span style="padding:5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i>Logout
        </button>
    </form>
}

Shop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Music Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Songs" asp-action="Index">Music Shop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-gear"></i> Management
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="RecordLabels" asp-action="Index"><i class="bi bi-record-circle"></i>Labels</a>
                                <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-headset"></i>Producers</a>
                                <a class="dropdown-item" asp-controller="Singers" asp-action="Index"><i class="bi bi-mic-fill"></i>Singers</a>

                            </div>
                        </li>
                        }
                        
                    </ul>
                    <form class="form-inline my-2 my-lg-0" asp-controller="Songs" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a Songs...">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>

                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                        
                    </ul>

                    
                    <partial name="_Identity.cshtml" />

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Shop
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>